### ISSUE TITLE
Support for Swiss QR?

### ISSUE THREAD

**Issue by vpetrovych** [metafloor/bwip-js#217]
It seems BWIPP supports Swiss QR, but I couldn't find reference in bwip-js. Is it possible to support it?

https://github.com/bwipp/postscriptbarcode/wiki/Swiss-QR-Code

**Comment by vpetrovych** [comment]
When I try to just use it with swissqrcode, I get the following error:

```
2:36:50 PM web.1 |  TypeError: $$.clip is not a function
2:36:50 PM web.1 |      at bwipp_swissqrcode (/Users/vladykx/Developer/barcode-gen/node_modules/bwip-js/dist/bwip-js-node.js:22846:12)
2:36:50 PM web.1 |      at bwipp_encode (/Users/vladykx/Developer/barcode-gen/node_modules/bwip-js/dist/bwip-js-node.js:35158:5)
2:36:50 PM web.1 |      at _Render (/Users/vladykx/Developer/barcode-gen/node_modules/bwip-js/dist/bwip-js-node.js:231:5)
2:36:50 PM web.1 |      at Object.ToBuffer [as toBuffer] (/Users/vladykx/Developer/barcode-gen/node_modules/bwip-js/dist/bwip-js-node.js:90:10)
```

**Comment by metafloor** [comment]
See issue #210.

**Comment by vpetrovych** [comment]
Sorry, missed that issue.
