### ISSUE TITLE
Bwipjs-api.metafloor.com is DOWN

### ISSUE THREAD

**Issue by ejhaswnec** [metafloor/bwip-js#223]
Hi there, Been working with Code128 barcodes via "http://bwipjs-api.metafloor.com/?bcid=code128&text="& but the server seems to be unresponsive in the last 24hrs. Wondering if anyone else has encountered the same issue and if any updates? Thanks again.

**Comment by ranjeet127** [comment]
I am also facing same issue.

**Comment by vagamente** [comment]
Me as well

**Comment by vagamente** [comment]
I think server needs a reboot.
Last week it didn't work too, and I think he solved it with a reboot.

![Immagine 2021-08-25 160657](https://user-images.githubusercontent.com/7126225/130805950-9d7aab58-3db3-4223-899a-da72a6862169.jpg)

**Comment by metafloor** [comment]
Just back from six days in the Yellowstone wilderness.  Not what one likes to see...

The API server uses greenlock-express for its https certificate handling and it appears the package has hit some kind of bug.  The node process is running at 100% CPU and the system journal is seeing the following being logged repeatedly:

```
Aug 25 08:21:58 ip-172-31-9-65 bwip-js-api[13480]: Error cert_renewal:
Aug 25 08:21:58 ip-172-31-9-65 bwip-js-api[13480]: socket hang up
Aug 25 08:21:58 ip-172-31-9-65 bwip-js-api[13480]: code: ECONNRESET
Aug 25 08:21:58 ip-172-31-9-65 bwip-js-api[13480]: Error: socket hang up
Aug 25 08:21:58 ip-172-31-9-65 bwip-js-api[13480]:     at connResetException (internal/errors.js:609:14)
Aug 25 08:21:58 ip-172-31-9-65 bwip-js-api[13480]:     at Socket.socketOnEnd (_http_client.js:453:23)
Aug 25 08:21:58 ip-172-31-9-65 bwip-js-api[13480]:     at Socket.emit (events.js:327:22)
Aug 25 08:21:58 ip-172-31-9-65 bwip-js-api[13480]:     at endReadableNT (_stream_readable.js:1221:12)
Aug 25 08:21:58 ip-172-31-9-65 bwip-js-api[13480]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

The vast majority of issues seen on the current AWS server is related to certificate handling.  Not sure why it is so unstable.

I suggest you switch to https://bwip-js.herokuapp.com/.  Same API interface.

**Comment by vagamente** [comment]
Switched and worked like a charme.
It seems a little bit faster too...

Good job, mate.

P.S.
It's awful when you come back from some relaxing days and there's the same stressful life waiting for you... trashing all your relax ;-)

**Comment by WoWFabler** [comment]
@metafloor Dear metafloor, thank you for your project

There is any chance to send you some money? I don't find any contact information, sorry for offtop request
