### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by Masber** [metafloor/bwip-js#254]
Hi,
I have a Vue app winch generates a pdf with a barcode, I got this working with `bwipjs.toCanvas` but I would like to use one encoder only (code128) so I can reduce my js bundle.

The version I am using is bwip-js@3.0.1

This is what I have done

```
import pdfMake from "pdfmake-lite/build/pdfmake.min";

import pdfFonts from "pdfmake-lite/build/vfs_fonts";
pdfMake.vfs = pdfFonts.pdfMake.vfs;

import { code128 } from "bwip-js";

export const label_TEST = {
  data() {
    return {};
  },
  methods: {
    printPDFWithBarcode() {
      let canvas = document.createElement("canvas");

      try {
        // The return value is the canvas element
        code128(   <<---------------------------------------------------------------------------- TypeError: Object(...)
          canvas,
          {
            bcid: "code128", // ap_article_id type
            text: "testbarcodetextvalue", // Text to encode
            scale: 1,
            height: 15, // Bar height, in millimeters
          },
          canvas
        );
      } catch (e) {
        console.error(e);
      }

      const trackingBarcode = canvas.toDataURL();

      const pdfContent = {
        content: [{ image: trackingBarcode, alignment: "center", colSpan: 2 }],
      };

      pdfMake
        .createPdf(pdfContent)
        .download("myfile.pdf");
    },
  },
};
```

But I the pdf has no barcode and the browser console complains about

```
TypeError: Object(...) is not a function
```

Any idea of what I am doing wrong?

thank you very much

**Comment by metafloor** [comment]
I don't see where you are passing in the canvas element to the `code128()` call, so that is probably the issue.

**Comment by Masber** [comment]
I must say I am not an expert in js.

sorry that was my bad, trying different things.

Also tried this:

```
      let canvas = document.createElement("canvas");

      try {
        // The return value is the canvas element
        code128(
          canvas,
          {
            bcid: "code128", // ap_article_id type
            text: returnDetails.shipment.trackingFrontMile, // Text to encode
            scale: 1,
            height: 15, // Bar height, in millimeters
          },
          canvas
        );
      } catch (e) {
        console.error(e);
      }

      const trackingBarcode = canvas.toDataURL();

      const pdfContent = {
        content: [{ image: trackingBarcode, alignment: "center", colSpan: 2 }],
      };

      pdfMake
        .createPdf(pdfContent)
        .download(returnDetails.shipment.trackingFrontMile + ".pdf");
    },
```

Getting same result

**Comment by metafloor** [comment]
Two things.  Please show how you are initializing/creating the `code128` function (`import`?).  And change your catch-handler to be `console.log(e.stack||e)`.  I would like to see the stack trace of the TypeError.

**Comment by metafloor** [comment]
BTW, you have now edited your code so that it is incorrect.  This is the function I think you are working with:
```
export function code128(opts,cvs) { return _ToCanvas(bwipp_code128,opts,cvs); };
```
Just put the options object first, and the canvas second.  The function does not take three parameters...

**Comment by Masber** [comment]
ok, tried removing the first parameter. Same error. The stack trace goes ends in my code.

stack trace
```
1.js:3460 TypeError: Object(...) is not a function
    at printLabel (1.js:3450:64)
    at ConsigneeReturnProductsForm.vue:1461:1
```
code
```
import pdfMake from "pdfmake-lite/build/pdfmake.min";

import pdfFonts from "pdfmake-lite/build/vfs_fonts";
pdfMake.vfs = pdfFonts.pdfMake.vfs;

import { code128 } from "bwip-js";

export const label_TEST = {
         data() {
           return {};
         },
         methods: {
           printPDFWithBarcode(returnDetails) {
             let canvas = document.createElement("canvas");

             try {
               // The return value is the canvas element
               code128(
                 {
                   bcid: "code128", // ap_article_id type
                   text: "barcodetexttest", // Text to encode
                   scale: 1,
                   height: 15, // Bar height, in millimeters
                 },
                 canvas
               );
             } catch (e) {
               console.error(e.stack || e);
             }

             const trackingBarcode = canvas.toDataURL();

             const pdfContent = {
               content: [
                 { image: trackingBarcode, alignment: "center", colSpan: 2 },
               ],
             };

             pdfMake
               .createPdf(pdfContent)
               .download(returnDetails.shipment.trackingFrontMile + ".pdf");
           },
         },
       };
```

**Comment by Masber** [comment]
Maybe this is easier to test. I have created a one page component.

```
<template>
  <div id="app">
  </div>
</template>

<script>
import pdfMake from "pdfmake-lite/build/pdfmake.min";

import pdfFonts from "pdfmake-lite/build/vfs_fonts";
pdfMake.vfs = pdfFonts.pdfMake.vfs;

import { gs1_128 } from "bwip-js";

export default {
  name: "App",
  mounted: function () {
    let canvas = document.createElement("canvas");

    try {
      // The return value is the canvas element
      gs1_128(
        {
          //  bcid: "code128", // ap_article_id type
          text: "barcodetexttest", // Text to encode
          scale: 1,
          height: 15, // Bar height, in millimeters
        },
        canvas
      );
    } catch (e) {
      console.error(e.stack || e);
    }

    const trackingBarcode = canvas.toDataURL();

    const pdfContent = {
      content: [{ image: trackingBarcode, alignment: "center", colSpan: 2 }],
    };

    pdfMake
      .createPdf(pdfContent)
      .download("myfile.pdf");
  },
};
</script>
```

and this is the stack trace

```
App.vue?234e:31 TypeError: Object(...) is not a function
    at VueComponent.mounted (App.vue?234e:21:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1863:1)
    at callHook (vue.runtime.esm.js?2b0e:4235:1)
    at Object.insert (vue.runtime.esm.js?2b0e:3158:1)
    at invokeInsertHook (vue.runtime.esm.js?2b0e:6390:1)
    at Vue.patch [as __patch__] (vue.runtime.esm.js?2b0e:6609:1)
    at Vue._update (vue.runtime.esm.js?2b0e:3960:1)
    at Vue.updateComponent (vue.runtime.esm.js?2b0e:4081:1)
    at Watcher.get (vue.runtime.esm.js?2b0e:4495:1)
    at new Watcher (vue.runtime.esm.js?2b0e:4484:1)
```

**Comment by metafloor** [comment]
The error is purely a vue issue - there is no bwip-js code in that stack trace.  I suspect vue has not imported the module when your code runs (imports are lazy/async loaded).  And `import` elements are live-views - that is why the weird object notation in the error message - it looks like it may be a proxy object.  You will need to do some research on when vue resolves imports and how to run your code after the import has been loaded.
