### ISSUE TITLE
Parameter 'includetext' throws error on 1.5.x

### ISSUE THREAD

**Issue by nlang** [metafloor/bwip-js#88]
After updating to the latest version, I suddenly get the following error as soon as I set 'includetext' to true. I tried 1.5.5 and 1.5.6 and then switched back to 1.4.2 where everything works fine. I'm using bwip-js on AWS Lambda with NodeJS 6.10

RangeError: Index out of range
    at checkOffset (buffer.js:831:11)
    at Buffer.readUInt16LE (buffer.js:877:5)
    at Object.getglyph (/var/task/node_modules/bwip-js/node-fonts.js:93:19)
    at BWIPJS.stringwidth (/var/task/node_modules/bwip-js/bwipjs.js:207:28)
    at BWIPJS.charpath (/var/task/node_modules/bwip-js/bwipjs.js:216:16)
    at Object.BWIPP.$0.renlinear (/var/task/node_modules/bwip-js/bwipp.js:25751:9)
    at Object.BWIPP.$0.code128 (/var/task/node_modules/bwip-js/bwipp.js:3112:7)
    at /var/task/node_modules/bwip-js/bwipp.js:26124:14
    at Function.module.exports.toBuffer (/var/task/node_modules/bwip-js/node-bwipjs.js:130:10)

**Comment by metafloor** [comment]
Please include some example code.

**Comment by nlang** [comment]
Executing the following on AWS Lambda NodeJS 6.10 results in the error in my original issue comment:
```
public test() {
    const bwipjs = require('bwip-js');

    const type = "code128";
    const content = "keepalive";

    const settings = {
        scaleX: '2',
        scaleY: '2',
        barcolor: '000000',
        backgroundcolor: 'FFFFFF',
        textcolor: '000000',
        paddingwidth: '5',
        paddingheight: '5',
        includetext: 1,
        bcid: type,
        text: content
    };

    bwipjs.toBuffer(settings, (err, buffer) => {
        if (!err) {
            console.log(buffer);
        } else {
            console.log("ERR", err);
        }
    });
}
```

**Comment by metafloor** [comment]
That code works against node 4.0 and 7.5.  I will have to setup a node 6 environment to test but I am thinking this is something in the AWS environment.

**Comment by nlang** [comment]
That might be the case, but it works fine on AWS with bwip-js 1.4.2. If I can help debugging on AWS or provide furhter infos let me know.

**Comment by metafloor** [comment]
Please do the following test.  In the file `node_modules/bwip-js/node-fonts.js` line 17, you should see:

```
var font = require('./fonts/fnt' + i + '-desc');
```

Change that to:
```
var font = require(__dirname + '/fonts/fnt' + i + '-desc');
```

**Comment by nlang** [comment]
Ok, I tried that but the result is the same. I logged a few things that might help you. In node-fonts.js in the getglyph function I logged (from line 89+)

`charcode, glyph, bytes, bytes.length, offset`. See output below:

```
2017-09-25 18:29:10.664 (+02:00)        a87e49b6-a20e-11e7-84eb-c1c96b98826b    charcode 16
2017-09-25 18:29:10.664 (+02:00)        a87e49b6-a20e-11e7-84eb-c1c96b98826b    glyph undefined
2017-09-25 18:29:10.665 (+02:00)        a87e49b6-a20e-11e7-84eb-c1c96b98826b    bytes <Buffer 7c 01 00 00 ef bf bd 01 00 00 ef bf bd 01 00 00 ef bf bd 01 00 00 ef bf bd 02 00 00 0f 03 00 00 ef bf bd 03 00 00 2d 04 00 00 4f 04 00 00 ef bf bd 04 ... >
2017-09-25 18:29:10.666 (+02:00)        a87e49b6-a20e-11e7-84eb-c1c96b98826b    bytes.length 19488
2017-09-25 18:29:10.666 (+02:00)        a87e49b6-a20e-11e7-84eb-c1c96b98826b    offset 104529920
2017-09-25 18:29:10.666 (+02:00)        a87e49b6-a20e-11e7-84eb-c1c96b98826b    ERR RangeError: Index out of range
    at checkOffset (buffer.js:831:11)
    at Buffer.readUInt16LE (buffer.js:877:5)
    at Object.getglyph (/var/task/node_modules/bwip-js/node-fonts.js:103:19)
    at BWIPJS.stringwidth (/var/task/node_modules/bwip-js/bwipjs.js:207:28)
    at BWIPJS.charpath (/var/task/node_modules/bwip-js/bwipjs.js:216:16)
    at Object.BWIPP.$0.renlinear (/var/task/node_modules/bwip-js/bwipp.js:25751:9)
    at Object.BWIPP.$0.code128 (/var/task/node_modules/bwip-js/bwipp.js:3112:7)
    at /var/task/node_modules/bwip-js/bwipp.js:26124:14
    at Function.module.exports.toBuffer (/var/task/node_modules/bwip-js/node-bwipjs.js:130:10)

```
As you see, bytes is way smaller then the offset. Hope that helps. Let me know if you need anything else.

**Comment by metafloor** [comment]
Thanks for the update.  That offset is total garbage.  And `bytes.length` does not correspond to any of the font files in the distro.  There may be some file corruption.

Can you please show the output from `ls -l fonts/*.bin` from the `bwip-js/` directory?

I am also concerned about the value for `charcode` (which has been converted to a glyph index at that point) - it maps to the digit `0`.  Was this from a different test string?

**Comment by nlang** [comment]
No, the string is the same ('keepalive').
See the directory output below.

```
$ ls -l fonts/*.bin
-rw-r--r-- 1 Nic Kein   3850 Sep  5 15:26 fonts/fnt0a-10.bin
-rw-r--r-- 1 Nic Kein 287227 Sep  5 15:26 fonts/fnt0a-108.bin
-rw-r--r-- 1 Nic Kein   5313 Sep  5 15:26 fonts/fnt0a-12.bin
-rw-r--r-- 1 Nic Kein   8210 Sep  5 15:26 fonts/fnt0a-16.bin
-rw-r--r-- 1 Nic Kein   9856 Sep  5 15:26 fonts/fnt0a-18.bin
-rw-r--r-- 1 Nic Kein  11417 Sep  5 15:26 fonts/fnt0a-20.bin
-rw-r--r-- 1 Nic Kein  16331 Sep  5 15:26 fonts/fnt0a-24.bin
-rw-r--r-- 1 Nic Kein  20454 Sep  5 15:26 fonts/fnt0a-27.bin
-rw-r--r-- 1 Nic Kein  23771 Sep  5 15:26 fonts/fnt0a-30.bin
-rw-r--r-- 1 Nic Kein  26275 Sep  5 15:26 fonts/fnt0a-32.bin
-rw-r--r-- 1 Nic Kein  32181 Sep  5 15:26 fonts/fnt0a-36.bin
-rw-r--r-- 1 Nic Kein  41352 Sep  5 15:26 fonts/fnt0a-40.bin
-rw-r--r-- 1 Nic Kein  52825 Sep  5 15:26 fonts/fnt0a-45.bin
-rw-r--r-- 1 Nic Kein  58996 Sep  5 15:26 fonts/fnt0a-48.bin
-rw-r--r-- 1 Nic Kein  64962 Sep  5 15:26 fonts/fnt0a-50.bin
-rw-r--r-- 1 Nic Kein  75626 Sep  5 15:26 fonts/fnt0a-54.bin
-rw-r--r-- 1 Nic Kein  78888 Sep  5 15:26 fonts/fnt0a-56.bin
-rw-r--r-- 1 Nic Kein  90384 Sep  5 15:26 fonts/fnt0a-60.bin
-rw-r--r-- 1 Nic Kein  98897 Sep  5 15:26 fonts/fnt0a-63.bin
-rw-r--r-- 1 Nic Kein 102905 Sep  5 15:26 fonts/fnt0a-64.bin
-rw-r--r-- 1 Nic Kein 122084 Sep  5 15:26 fonts/fnt0a-70.bin
-rw-r--r-- 1 Nic Kein 133252 Sep  5 15:26 fonts/fnt0a-72.bin
-rw-r--r-- 1 Nic Kein   3128 Sep  5 15:26 fonts/fnt0a-8.bin
-rw-r--r-- 1 Nic Kein 159753 Sep  5 15:26 fonts/fnt0a-80.bin
-rw-r--r-- 1 Nic Kein 159444 Sep  5 15:26 fonts/fnt0a-81.bin
-rw-r--r-- 1 Nic Kein 178306 Sep  5 15:26 fonts/fnt0a-84.bin
-rw-r--r-- 1 Nic Kein   3502 Sep  5 15:26 fonts/fnt0a-9.bin
-rw-r--r-- 1 Nic Kein 196655 Sep  5 15:26 fonts/fnt0a-90.bin
-rw-r--r-- 1 Nic Kein 224580 Sep  5 15:26 fonts/fnt0a-96.bin
-rw-r--r-- 1 Nic Kein   3850 Sep  5 15:26 fonts/fnt0m-10.bin
-rw-r--r-- 1 Nic Kein 287227 Sep  5 15:26 fonts/fnt0m-108.bin
-rw-r--r-- 1 Nic Kein   4849 Sep  5 15:26 fonts/fnt0m-12.bin
-rw-r--r-- 1 Nic Kein   7147 Sep  5 15:26 fonts/fnt0m-16.bin
-rw-r--r-- 1 Nic Kein   9865 Sep  5 15:26 fonts/fnt0m-18.bin
-rw-r--r-- 1 Nic Kein  11426 Sep  5 15:26 fonts/fnt0m-20.bin
-rw-r--r-- 1 Nic Kein  16086 Sep  5 15:26 fonts/fnt0m-24.bin
-rw-r--r-- 1 Nic Kein  18803 Sep  5 15:26 fonts/fnt0m-27.bin
-rw-r--r-- 1 Nic Kein  23756 Sep  5 15:26 fonts/fnt0m-30.bin
-rw-r--r-- 1 Nic Kein  26275 Sep  5 15:26 fonts/fnt0m-32.bin
-rw-r--r-- 1 Nic Kein  32181 Sep  5 15:26 fonts/fnt0m-36.bin
-rw-r--r-- 1 Nic Kein  41371 Sep  5 15:26 fonts/fnt0m-40.bin
-rw-r--r-- 1 Nic Kein  52825 Sep  5 15:26 fonts/fnt0m-45.bin
-rw-r--r-- 1 Nic Kein  58996 Sep  5 15:26 fonts/fnt0m-48.bin
-rw-r--r-- 1 Nic Kein  64962 Sep  5 15:26 fonts/fnt0m-50.bin
-rw-r--r-- 1 Nic Kein  75626 Sep  5 15:26 fonts/fnt0m-54.bin
-rw-r--r-- 1 Nic Kein  78888 Sep  5 15:26 fonts/fnt0m-56.bin
-rw-r--r-- 1 Nic Kein  90356 Sep  5 15:26 fonts/fnt0m-60.bin
-rw-r--r-- 1 Nic Kein  98897 Sep  5 15:26 fonts/fnt0m-63.bin
-rw-r--r-- 1 Nic Kein 102905 Sep  5 15:26 fonts/fnt0m-64.bin
-rw-r--r-- 1 Nic Kein 122084 Sep  5 15:26 fonts/fnt0m-70.bin
-rw-r--r-- 1 Nic Kein 133252 Sep  5 15:26 fonts/fnt0m-72.bin
-rw-r--r-- 1 Nic Kein   3100 Sep  5 15:26 fonts/fnt0m-8.bin
-rw-r--r-- 1 Nic Kein 159753 Sep  5 15:26 fonts/fnt0m-80.bin
-rw-r--r-- 1 Nic Kein 159444 Sep  5 15:26 fonts/fnt0m-81.bin
-rw-r--r-- 1 Nic Kein 178345 Sep  5 15:26 fonts/fnt0m-84.bin
-rw-r--r-- 1 Nic Kein   3496 Sep  5 15:26 fonts/fnt0m-9.bin
-rw-r--r-- 1 Nic Kein 196655 Sep  5 15:26 fonts/fnt0m-90.bin
-rw-r--r-- 1 Nic Kein 224623 Sep  5 15:26 fonts/fnt0m-96.bin
-rw-r--r-- 1 Nic Kein   3848 Sep  5 15:26 fonts/fnt1a-10.bin
-rw-r--r-- 1 Nic Kein 271515 Sep  5 15:26 fonts/fnt1a-108.bin
-rw-r--r-- 1 Nic Kein   5183 Sep  5 15:26 fonts/fnt1a-12.bin
-rw-r--r-- 1 Nic Kein   7767 Sep  5 15:26 fonts/fnt1a-16.bin
-rw-r--r-- 1 Nic Kein   9087 Sep  5 15:26 fonts/fnt1a-18.bin
-rw-r--r-- 1 Nic Kein  10951 Sep  5 15:26 fonts/fnt1a-20.bin
-rw-r--r-- 1 Nic Kein  15678 Sep  5 15:26 fonts/fnt1a-24.bin
-rw-r--r-- 1 Nic Kein  18590 Sep  5 15:26 fonts/fnt1a-27.bin
-rw-r--r-- 1 Nic Kein  22492 Sep  5 15:26 fonts/fnt1a-30.bin
-rw-r--r-- 1 Nic Kein  24365 Sep  5 15:26 fonts/fnt1a-32.bin
-rw-r--r-- 1 Nic Kein  29971 Sep  5 15:26 fonts/fnt1a-36.bin
-rw-r--r-- 1 Nic Kein  39190 Sep  5 15:26 fonts/fnt1a-40.bin
-rw-r--r-- 1 Nic Kein  48454 Sep  5 15:26 fonts/fnt1a-45.bin
-rw-r--r-- 1 Nic Kein  54127 Sep  5 15:26 fonts/fnt1a-48.bin
-rw-r--r-- 1 Nic Kein  58564 Sep  5 15:26 fonts/fnt1a-50.bin
-rw-r--r-- 1 Nic Kein  68741 Sep  5 15:26 fonts/fnt1a-54.bin
-rw-r--r-- 1 Nic Kein  73566 Sep  5 15:26 fonts/fnt1a-56.bin
-rw-r--r-- 1 Nic Kein  85189 Sep  5 15:26 fonts/fnt1a-60.bin
-rw-r--r-- 1 Nic Kein  94769 Sep  5 15:26 fonts/fnt1a-63.bin
-rw-r--r-- 1 Nic Kein  98513 Sep  5 15:26 fonts/fnt1a-64.bin
-rw-r--r-- 1 Nic Kein 114330 Sep  5 15:26 fonts/fnt1a-70.bin
-rw-r--r-- 1 Nic Kein 119744 Sep  5 15:26 fonts/fnt1a-72.bin
-rw-r--r-- 1 Nic Kein   3005 Sep  5 15:26 fonts/fnt1a-8.bin
-rw-r--r-- 1 Nic Kein 149870 Sep  5 15:26 fonts/fnt1a-80.bin
-rw-r--r-- 1 Nic Kein 150779 Sep  5 15:26 fonts/fnt1a-81.bin
-rw-r--r-- 1 Nic Kein 167549 Sep  5 15:26 fonts/fnt1a-84.bin
-rw-r--r-- 1 Nic Kein   3345 Sep  5 15:26 fonts/fnt1a-9.bin
-rw-r--r-- 1 Nic Kein 187839 Sep  5 15:26 fonts/fnt1a-90.bin
-rw-r--r-- 1 Nic Kein 208348 Sep  5 15:26 fonts/fnt1a-96.bin
-rw-r--r-- 1 Nic Kein   3846 Sep  5 15:26 fonts/fnt1m-10.bin
-rw-r--r-- 1 Nic Kein 271681 Sep  5 15:26 fonts/fnt1m-108.bin
-rw-r--r-- 1 Nic Kein   4745 Sep  5 15:26 fonts/fnt1m-12.bin
-rw-r--r-- 1 Nic Kein   6989 Sep  5 15:26 fonts/fnt1m-16.bin
-rw-r--r-- 1 Nic Kein   9093 Sep  5 15:26 fonts/fnt1m-18.bin
-rw-r--r-- 1 Nic Kein  11042 Sep  5 15:26 fonts/fnt1m-20.bin
-rw-r--r-- 1 Nic Kein  14650 Sep  5 15:26 fonts/fnt1m-24.bin
-rw-r--r-- 1 Nic Kein  17546 Sep  5 15:26 fonts/fnt1m-27.bin
-rw-r--r-- 1 Nic Kein  22476 Sep  5 15:26 fonts/fnt1m-30.bin
-rw-r--r-- 1 Nic Kein  24394 Sep  5 15:26 fonts/fnt1m-32.bin
-rw-r--r-- 1 Nic Kein  29945 Sep  5 15:26 fonts/fnt1m-36.bin
-rw-r--r-- 1 Nic Kein  39371 Sep  5 15:26 fonts/fnt1m-40.bin
-rw-r--r-- 1 Nic Kein  48662 Sep  5 15:26 fonts/fnt1m-45.bin
-rw-r--r-- 1 Nic Kein  54193 Sep  5 15:26 fonts/fnt1m-48.bin
-rw-r--r-- 1 Nic Kein  58691 Sep  5 15:26 fonts/fnt1m-50.bin
-rw-r--r-- 1 Nic Kein  68819 Sep  5 15:26 fonts/fnt1m-54.bin
-rw-r--r-- 1 Nic Kein  73626 Sep  5 15:26 fonts/fnt1m-56.bin
-rw-r--r-- 1 Nic Kein  85279 Sep  5 15:26 fonts/fnt1m-60.bin
-rw-r--r-- 1 Nic Kein  94846 Sep  5 15:26 fonts/fnt1m-63.bin
-rw-r--r-- 1 Nic Kein  98673 Sep  5 15:26 fonts/fnt1m-64.bin
-rw-r--r-- 1 Nic Kein 114410 Sep  5 15:26 fonts/fnt1m-70.bin
-rw-r--r-- 1 Nic Kein 119908 Sep  5 15:26 fonts/fnt1m-72.bin
-rw-r--r-- 1 Nic Kein   2993 Sep  5 15:26 fonts/fnt1m-8.bin
-rw-r--r-- 1 Nic Kein 149954 Sep  5 15:26 fonts/fnt1m-80.bin
-rw-r--r-- 1 Nic Kein 150785 Sep  5 15:26 fonts/fnt1m-81.bin
-rw-r--r-- 1 Nic Kein 167823 Sep  5 15:26 fonts/fnt1m-84.bin
-rw-r--r-- 1 Nic Kein   3339 Sep  5 15:26 fonts/fnt1m-9.bin
-rw-r--r-- 1 Nic Kein 188010 Sep  5 15:26 fonts/fnt1m-90.bin
-rw-r--r-- 1 Nic Kein 208638 Sep  5 15:26 fonts/fnt1m-96.bin
-rw-r--r-- 1 Nic Kein    992 Aug 29 23:21 fonts/fnt2a-10.bin
-rw-r--r-- 1 Nic Kein   3826 Aug 29 23:21 fonts/fnt2a-20.bin
-rw-r--r-- 1 Nic Kein   8570 Aug 29 23:21 fonts/fnt2a-30.bin
-rw-r--r-- 1 Nic Kein  15254 Aug 29 23:22 fonts/fnt2a-40.bin
-rw-r--r-- 1 Nic Kein  23776 Aug 29 23:22 fonts/fnt2a-50.bin
-rw-r--r-- 1 Nic Kein  34274 Aug 29 23:22 fonts/fnt2a-60.bin
-rw-r--r-- 1 Nic Kein  46666 Aug 29 23:22 fonts/fnt2a-70.bin
-rw-r--r-- 1 Nic Kein  60790 Aug 29 23:22 fonts/fnt2a-80.bin
-rw-r--r-- 1 Nic Kein  77152 Aug 29 23:23 fonts/fnt2a-90.bin
-rw-r--r-- 1 Nic Kein    986 Aug 29 23:21 fonts/fnt2m-10.bin
-rw-r--r-- 1 Nic Kein   3814 Aug 29 23:21 fonts/fnt2m-20.bin
-rw-r--r-- 1 Nic Kein   8490 Aug 29 23:21 fonts/fnt2m-30.bin
-rw-r--r-- 1 Nic Kein  15142 Aug 29 23:22 fonts/fnt2m-40.bin
-rw-r--r-- 1 Nic Kein  23722 Aug 29 23:22 fonts/fnt2m-50.bin
-rw-r--r-- 1 Nic Kein  34230 Aug 29 23:22 fonts/fnt2m-60.bin
-rw-r--r-- 1 Nic Kein  46458 Aug 29 23:22 fonts/fnt2m-70.bin
-rw-r--r-- 1 Nic Kein  60790 Aug 29 23:22 fonts/fnt2m-80.bin
-rw-r--r-- 1 Nic Kein  77050 Aug 29 23:23 fonts/fnt2m-90.bin

```

**Comment by metafloor** [comment]
There must be something with the AWS platform that is non-standard.  From your console output, this is the tell:
```
84eb-c1c96b98826b    bytes <Buffer 7c 01 00 00 ef bf bd 01 00 00 ef bf bd 01 00 00 ef bf bd 01
```

This is what it the buffer is supposed to look like:
```
> fs.readFileSync('fonts/fnt1a-20.bin')
<Buffer 7c 01 00 00 86 01 00 00 bd 01 00 00 f1 01 00 00 87 02 00 00 0f 03 00 00 97 03
```
It appears the buffer is being converted to UTF-8.  `ef bf bd` is the UTF-8 sequence for UNICODE REPLACEMENT CHARACTER (U+FFFD).  My guess is that AWS is fetching the data across an HTTP transport, which is causing the conversion.

Since I don't know that platform, I cannot really help you any further.  One possibility though: Is there an option to set MIME types for different file extensions?  If so, try setting `.bin` to `application/octet-stream`.

**Comment by nlang** [comment]
Ok, thanks. So now I know where to look for the cause. I think maybe it would be better to specify the encoding as 2nd parameter to `fs.readFileSync` to avoid such problems?

**Comment by metafloor** [comment]
Specifying an encoding would cause a string to be returned.  The code needs a buffer as the data is binary.

**Comment by nlang** [comment]
Works now on AWS Lambda 👍
